[package]
authors = ["Dan Reeves <hey@danreev.es>"]
edition = "2018"
name = "battery-status"
repository = "https://github.com/danreeves/battery-status"
version = "0.1.0"
[[bin]]
doc = false
name = "battery-status"

[dependencies]
battery = "0.7.5"
regex = "1.3.4"
structopt = "0.3.11"
